### PR TITLE
Setup base runner for ts

### PR DESCRIPTION
**Pull request by nully0x**
This PR introduces a robust test runner system that integrates with RabbitMQ for message queuing. The system is designed to clone repositories, execute tests in a controlled environment using Nix, and report results back through RabbitMQ.

## Key Features

1. **Language-Specific Configurations**: Supports multiple programming languages with customizable setup and run commands.
2. **RabbitMQ Integration**: Uses RabbitMQ for receiving test run requests and sending test results.
3. **Nix-based Execution**: Leverages Nix shells for consistent and isolated test environments.
4. **Git Repository Handling**: Clones repositories, checks out specific commits, and cleans up after execution.
5. **Modular Design**: Separates concerns into distinct modules for better maintainability.
6. **Dockerized with nix packs**: I also implemented Nix in docker so we can orchestrate code run within docker since we are running the entire stack in k8s.

## Implementation Details

- `config/config.ts`: Defines language-specific configurations and helper functions.
- `config/rabbitmq.ts`: Sets up RabbitMQ connection and provides queue management.
- `models/types.ts`: Defines TypeScript interfaces for test requests, results, and stages.
- `server.ts`: Initializes the Express server and RabbitMQ consumer.
- `utils/`:
  - `gitUtils.ts`: Handles Git operations (cloning, checkout, clean-up).
  - `logger.ts`: Provides logging functionality.
  - `nixRunner.ts`: Executes commands in Nix shell environments.
  - `resultReporter.ts`: Reports test results back to RabbitMQ.
  - `runner.ts`: Orchestrates the overall test process.
  - `testExecutor.ts`: Executes individual test stages.

## Current Limitations

- Only TypeScript/JavaScript projects are fully supported.
- Error handling and reporting could be enhanced for more specific scenarios.

## Next Steps

- Implement support for additional programming languages.
- Enhance error handling and provide more detailed error reporting.
- Add more comprehensive logging throughout the system.
- Implement unit and integration tests for the test runner components.

## Testing

- Manual testing has been performed with TypeScript projects.
- RabbitMQ integration has been verified for message passing.

## Reviewers

Please focus on:
- The overall architecture and flow of the test execution process.
- RabbitMQ integration and error handling.
- Extensibility for adding support for new languages.
- Security considerations, especially in repository handling and command execution.

### CODE REVIEW

**Review by daviroo — COMMENTED** [review]
There are no issues with any of the code in this PR but I do want to get consensus on the overall approach.  Right now the test runner will run the tests which in turn will run the users code in a child process on the server itself.  This doesn't seem very secure for us to be running code which could theoretically be doing anything.  Instead I think we should do something similar to what [saving satoshi](https://github.com/saving-satoshi/saving-satoshi-backend/blob/master/src/lib/docker.ts) does which is to run the executing code in a docker container.  What do you guys think? @nully0x @Extheoisah

**Comment by nully0x** [comment]
oh, I describe how it works in the PR description, we I am actually running it inside of docker container, which is actually secure with an extra layer of running it with isolated nix shell on the docker container itself. 

This approach is nix in docker more like docker in VM(EC2 instance we use for saving satoshi but in this case its a container in kubernetes.)

The bottom line is that is run with nix with is also isolated.

**Comment by daviroo** [comment]
> oh, I describe how it works in the PR description, we I am actually running it inside of docker container, which is actually secure with an extra layer of running it with isolated nix shell on the docker container itself.
> 
> This approach is nix in docker more like docker in VM(EC2 instance we use for saving satoshi but in this case its a container in kubernetes.)
> 
> The bottom line is that is run with nix with is also isolated.

I think nix only provides isolation for dependencies.  I don't think it prevents access to disk or network etc.  Can you find any docs about the level of isolation provided by nix?

**Comment by Extheoisah** [comment]
@daviroo I think what @nully0x is saying is that he's running the code using Nix inside of docker. So he's containerizing everything and tearing it down after. 
I didn't look at the code in-depth so correct me if I'm wrong

**Comment by daviroo** [comment]
> @daviroo I think what @nully0x is saying is that he's running the code using Nix inside of docker. So he's containerizing everything and tearing it down after. I didn't look at the code in-depth so correct me if I'm wrong

The only docker container is the one running the queue consumer which runs the users code in a nix shell.  AFAIK nix doesn't provide isolation for things other than some shell stuff for managing project dependencies.  So theoretically someone could write code which brings down the test runner.

**Comment by nully0x** [comment]
There are some checks we can put in place as regards that, inclusive of turning on nix sandbox feature, it's currently off for now for testing purposes.

**Comment by nully0x** [comment]
There are some checks we can put in place as regards that, inclusive of turning on nix sandbox feature, it's currently off for now for testing purposes.

**Comment by daviroo** [comment]
> There are some checks we can put in place as regards that, inclusive of turning on nix sandbox feature, it's currently off for now for testing purposes.

Ok this might be an option.  Can you find any docs about how this works?  I can't find any.

**Comment by daviroo** [comment]
@nully0x has this been superseded by #2 ?

**Comment by nully0x** [comment]
Yes, we can close/discard this.

**Pull request closed without merging**
